# ------------------------------------
# Server Monitor Configuration File
# ------------------------------------

# Maximum allowed disk usage percentage (Alerts if exceeded)
MAX_DISK_USAGE=80

# Minimum free RAM in Megabytes (Alerts if actual free RAM is below this)
MIN_FREE_RAM=500
